name: ChatColor-Folia

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs: 
  ChatColor-Folia:
    uses: Dungjava/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Dungjava/ChatColor-Folia"
      name: "ChatColor-Folia"
      target: "target/*.jar"
      java: 21
 
